CREATE DATABASE IF NOT EXISTS student_advisor;
USE student_advisor;

CREATE TABLE IF NOT EXISTS dosen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nip VARCHAR(20) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  jurusan VARCHAR(100) NOT NULL,
  jabatan VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS mahasiswa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nim VARCHAR(20) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  jurusan VARCHAR(100) NOT NULL,
  semester INT NOT NULL,
  dosen_id INT,
  FOREIGN KEY (dosen_id) REFERENCES dosen(id) ON DELETE SET NULL
);
